### ISSUE TITLE
problem on run adka

### ISSUE THREAD

**Issue by igotfr** [apiel/adka#2]
after install adka and run I receive the message

[notecomm@localhost pages]$ adka
• ROOT_FOLDER /home/notecomm/pdeno/adka/src/pages
• info Run adka
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:10)
    at async Object.lstat ($deno$/ops/fs/stat.ts:79:15)
    at async copy (copy.ts:239:19)
    at async adka (adka.ts:17:5)

**Comment by apiel** [comment]
Which version of deno are you using?

**Comment by apiel** [comment]
did you create a folder `src/pages`. Does this folder contain a page like described here https://github.com/apiel/adka#getting-started ?

**Comment by igotfr** [comment]
@apiel yes I created, I specified on ROOT_FOLDER, inside the folder I created the script index.page.tsx with the content

```js
/// <reference path="../jsx.d.ts" />
import {
  React
} from "https://raw.githubusercontent.com/apiel/adka/master/mod.ts";

export function Hello() {
  return <p>Hello.</p>;
}
```

and I run adka on the same folder as index.page.tsx

**Comment by apiel** [comment]
Try to run adka from ` /home/notecomm/pdeno/adka`. If it solve the problem, then let me know, it might be something I have to fix.

**Comment by igotfr** [comment]
> Try to run adka from ` /home/notecomm/pdeno/adka`. If it solve the problem, then let me know, it might be something I have to fix.

I run on  /home/notecomm/pdeno/adka and I got the same error message

[notecomm@localhost pages]$ deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2

**Comment by apiel** [comment]
I updated adka_server with the latest version of oak. Try to re-install adka and see if you still have the problem.

**Comment by igotfr** [comment]
> I updated adka_server with the latest version of oak. Try to re-install adka and see if you still have the problem.

it didn't solve, I'm with the same problem

**Comment by apiel** [comment]
This is strange :-/ do you have repo so i can look at the code?

**Comment by igotfr** [comment]
> This is strange :-/ do you have repo so i can look at the code?

repo of my entire deno deps?

**Comment by apiel** [comment]
no no of your tests...

**Comment by igotfr** [comment]
> no no of your tests...

I just created the folder and the script, I didn't understand about the tests

**Comment by apiel** [comment]
ok I managed to reproduce. It's getting late, I will try to have a look tomorrow.

**Comment by igotfr** [comment]
> ok I managed to reproduce. It's getting late, I will try to have a look tomorrow.

ok, you can make a remote connection on my pc if you want

**Comment by apiel** [comment]
I think I managed to fix it in https://github.com/apiel/adka/commit/5f8a0d61846983c175d24bdfc2a613624abc51b7
You need to reload dependency again ...

By the way a page component should look like this:

```tsx
/// <reference path="../jsx.d.ts" />
import { React, page } from "https://raw.githubusercontent.com/apiel/adka/master/mod.ts";

function Main() {
    return (
        <div>
            <h1>Main page</h1>
            <p>This is an example</p>
        </div>
    );
}

export default page(Main);
```
It should export the component as default wrapped into `page()` function.

**Comment by igotfr** [comment]
> I think I managed to fix it in [5f8a0d6](https://github.com/apiel/adka/commit/5f8a0d61846983c175d24bdfc2a613624abc51b7)
> You need to reload dependency again ...
> 
> By the way a page component should look like this:
> 
> ```tsx
> /// <reference path="../jsx.d.ts" />
> import { React, page } from "https://raw.githubusercontent.com/apiel/adka/master/mod.ts";
> 
> function Main() {
>     return (
>         <div>
>             <h1>Main page</h1>
>             <p>This is an example</p>
>         </div>
>     );
> }
> 
> export default page(Main);
> ```
> 
> It should export the component as default wrapped into `page()` function.

[notecomm@localhost pages]$ adka
• ROOT_FOLDER /home/notecomm/pdeno/adka/src/pages
• info Run adka
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:10)
    at async Object.[Symbol.asyncIterator] ($deno$/ops/fs/read_dir.ts:31:14)
    at async walk (walk.ts:105:20)
    at async generatePages (generatePages.ts:19:22)
    at async adka (adka.ts:27:5)

**Comment by apiel** [comment]
Sorry, I was busy this last day. This is because you are setting the wrong path for the root folder. Your root folder should be `/home/notecomm/pdeno/adka` instead of `/home/notecomm/pdeno/adka/src/pages`.

See an example here: https://github.com/apiel/adka-issue-2
```sh
git clone https://github.com/apiel/adka-issue-2.git
cd adka-issue-2
deno run --allow-read --allow-write --allow-env --allow-net --unstable https://raw.githubusercontent.com/apiel/adka/master/adka.ts
```

**Comment by igotfr** [comment]
> Sorry, I was busy this last day. This is because you are setting the wrong path for the root folder. Your root folder should be `/home/notecomm/pdeno/adka` instead of `/home/notecomm/pdeno/adka/src/pages`.
> 
> See an example here: https://github.com/apiel/adka-issue-2
> 
> ```shell
> git clone https://github.com/apiel/adka-issue-2.git
> cd adka-issue-2
> deno run --allow-read --allow-write --allow-env --allow-net --unstable https://raw.githubusercontent.com/apiel/adka/master/adka.ts
> ```

thanks
